language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-27.0.1
    - android-27
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-27
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
 - chmod +x gradlew

script: ./gradlew testRelease assembleRelease
